### ISSUE TITLE
Are you accepting PRs?

### ISSUE THREAD

**Issue by ruohoruotsi** [jhasegaw/phonecodes#1]
Hiya, thanks for your very interesting and useful repo. 👏 👏 

I've made a fork to study, as part of my work on a [Yorùbá g2p ](https://github.com/Niger-Volta-LTI/yoruba-text) notably to then do `ipa2arpabet` for use inna Kaldi rig. In the course of examining the code and working through the tests, I cleaned up some of the tests in a way that they could be run more easily from a Travis/Jenkins or other build-bot system, which might be a nice if you were to make a submission to PyPI, so folks might `pip install phonecodes`. 

Sooooo ... longwindedly, my question is: Are you open to PRs? And generally I'm curious about your plans/ambitions for this repo. I work on [West African](https://github.com/Niger-Volta-LTI) languages and think this work can be helpful to bring new languages online regardless of what format of existing lexicographic work.

**Comment by jhasegaw** [comment]
Wow, thanks!  Yes, I think I could field a PR.

Plans/ambitions... tough to say.  I'm interested in making the work useful to other people, but finding the time to make that happen is a bit of a challenge.  Thanks.

**Comment by ruohoruotsi** [comment]
Sounds good. I'll prepare a PR. No stress on the plans, I was just curious. I do think the code is very useful and approachable as is!
